config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "articles#index"
  get "myarticles", to: "articles#my"
  get 'pending_approve', to: "articles#pending_approve"
  resources :articles do
    member do
      post 'approve', to: "articles#approve"
    end
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
  belongs_to :user

  validates :body, presence: true

  before_validation :ensure_commenter_has_value, on: :create

  private
    def ensure_commenter_has_value
      if commenter.blank?
        self.commenter = "Anonymous"
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :articles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    role == 1
  end

  def user?
    role == 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    { locale: I18n.locale }
  end


  def after_sign_in_path_for(resource)
    stored_location_for(resource) || root_path(locale: I18n.locale)
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path(locale: I18n.locale)
  end

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [ :show, :edit, :update, :destroy, :approve ]
  before_action :authenticate_user!, only: [ :new, :create, :my, :update ]

  def index
    @articles = Article.where(visible: "public", status: 1)
  end

  def my
    @articles = Article.where(["user_id = ?", current_user.id])
    render :index
  end

  def pending_approve
    @articles = Article.where(visible: 'public', status: 0)
  end

  def approve
    authorize @article, :can_approve?
    # Reject: -1, pending: 0, accept: 1
    @article.update(status: params[:status])

    redirect_to :pending_approve
  end

  def show
    # @article = Article.find(params[:id])
    @comments = Comment.where(article_id: @article.id, visible: 'public')
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params.merge(user_id: current_user.id))

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    # @article = Article.find(params[:id])

    if @article.update(article_params.merge(user_id: current_user.id))
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :visible)
    end

    def find_article
      @article = Article.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, on: [:create]

  def create
    @article = Article.find(params[:article_id])
    # Ask
    Comment.create(comment_params.merge(article_id: @article.id, user_id: current_user.id)) # Create! vs Create
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :visible)
    end
end

app/controllers/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_VISIBLE = [ "public", "private", "archived" ]

  included do
    validates :visible, inclusion: { in: Visible::VALID_VISIBLE }
  end

  def archived?
    visible == "archived"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_comment.erb
<div class="comment">
  <img src="https://placehold.co/30x30/000000/FFF" alt="Avatar">
  <div class="comment__content">
    <div class="comment__metadata">
      <span><strong><%= comment.commenter%></strong></span>
      <span>Time</span>
    </div>
    <div><%= comment.body %></div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div class="form-group">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control'%>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_area :body, class: 'form-control'%>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :visible, class: 'form-label' %><br>
    <%= form.select :visible, Visible::VALID_VISIBLE, class: 'form-select', selected: article.visible || 'public' %>
  </div>

  <div class="form-group">
    <%= form.submit t(:create_article, scope: [:articles, :form]), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h4>Explore</h4>
<div class="container">
    <div class="row row-cols-2">
      <% @articles.each do |article| %>
          <div class="card me-3 mb-3" style="width: 18rem;">
            <img src="https://placehold.co/600x500/000000/FFF" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title"><%= article.title%></h5>
              <%# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> %>
              <a href="<%= article_path(article)%>" class="btn btn-primary">Read</a>
            </div>
          </div>
      <% end %>
    </div>
  </div>

app/views/articles/new.html.erb
<h1><%= t(:create_article, scope: [:articles, :form])%></h1>

<%= render 'form', article: @article %>

app/views/articles/pending_approve.html.erb
<h1>Pending approve</h1>
<div class="container">
  <% @articles&.each do |article| %>
    <div class="border rounded p-2 m-2 flex">
      <p><%= article.title %></p>

      <%= link_to "View article", article_path(article), target: "_blank" %>

      <%= form_with url: approve_article_path(article), method: :post do |f| %>
        <%= f.hidden_field :status, value: 1 %>
        <%= f.submit 'Approve', class: 'btn btn-primary' %>
      <% end %>

      <!-- Rejection Form -->
      <%= form_with url: approve_article_path(article), method: :post do |f| %>
        <%= f.hidden_field :status, value: -1 %>
        <%= f.submit 'Reject', class: 'btn btn-cancle' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/articles/show.html.erb
<%# <button class="btn btn-outline">
  <i class="bi bi-caret-left-fill"></i>
  Back
</button> %>
<h1 class="text-center"><%= @article.title%></h1>
<div class="mt-2 p-2"><%= @article.body %></div>

<div>
  <%= link_to "Edit", edit_article_path(@article) %>
  <%=
    link_to "Destroy",
    article_path(@article),
    data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    }
  %>
</div>

<div class="container mt-2 p-2 mb-2">
  <h4>Comments</h4>
  <div>
    <%= render partial: 'comment', collection: @comments, as: :comment %>
  </div>
  <div class="row rounded border p-2">
    <h4>Leave your comment here:</h4>
    <%= render "comments/form", article: @article %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [article, article.comments.build], class: 'form' do |form| %>
  <div class="form-group mb-1">
    <%= form.label :commenter, class: 'form-label' %>
    <%= form.text_field :commenter, class: 'form-control' %>
  </div>
  <div class="form-group mb-1">
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group mb-1">
    <%= form.label :visible, class: 'form-label' %><br>
    <%= form.select :visible, Visible::VALID_VISIBLE, selected: 'public', class: 'form-select' %>
  </div>
  <div class="form-group mb-1">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">MyBlog</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/"><%= t(:articles, scope: [:application, :nav]) %></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/myarticles"><%= t(:my_articles, scope: [:application, :nav]) %></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= new_article_path %>"><%= t(:create, scope: [:application, :nav]) %></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= pending_approve_path %>"><%= t(:approve_article, scope: [:application, :nav]) %></a>
              </li>
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "Profile", edit_user_registration_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>
                <% else %>
                <li class="nav-item flex-end">
                  <%= link_to t(:login, scope: [:application, :nav]), new_user_session_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <div class="container mt-3">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>